### ISSUE TITLE
Run start-up script

### ISSUE THREAD

**Issue by DatKyle** [tfenster/mssql-image#5]
We have a couple of databases that require `ALTER DATABASE [database] SET TRUSTWORTHY ON`; it is a bit of a pain to run the script every time we start the containers.

Could we add the ability to run start-up scripts?

I was thinking of creating a folder called `start-up`, and it will loop through each SQL file in that folder and run them.

**Comment by tfenster** [comment]
@DatKyle Great idea! I would prefer to give it a bit more flexibility with a `before-startup` and `after-startup` folder. The logic should be exactly as you describe, get the scripts in the folder and run them in alphabetical order. The scripts in `before-startup` are called here https://github.com/tfenster/mssql-image/blob/main/start.ps1#L9 and the scripts in `after-startup` are called here https://github.com/tfenster/mssql-image/blob/main/start.ps1#L67. The only thing I would change is that I would make it PowerShell scripts instead of SQL. That would also give people more flexibility to do other things than "only" running SQL

Do you agree? And do you want to give it a try yourself? I'd be very happy to get your contribution

**Comment by DatKyle** [comment]
@tfenster, Yeah completely agree, PowerShell instead of SQL and the before and after scripts are good shouts, making it more flexible. and I'm more than happy to contribute :)

**Comment by tfenster** [comment]
Great! Looking forward to your PR :)

**Comment by DatKyle** [comment]
Hi @tfenster,

I've made the script changes, but do you want the paths to be hardcoded or environment variables?
I was thinking of doing environment variables but allowing if left blank then fall back to a default path.

**Comment by tfenster** [comment]
That sounds great 👍

**Comment by tfenster** [comment]
@DatKyle Builds have started, see https://github.com/tfenster/mssql-image/runs/5007129901?check_suite_focus=true. I had to fix one additional typo (https://github.com/tfenster/mssql-image/commit/8af1a02de5fb630e0d518bad85522b275e4911a0) but it seems to run fine now. Could you try with 2019 CU 11 if the logic works as expected? If you confirm, then I will kick off the other builds

**Comment by tfenster** [comment]
CU 11 images are done

**Comment by DatKyle** [comment]
Tested using `tobiasfenster/mssql-server-dev-unsupported:2019-cu11-ltsc2019` all is good 👍
![image](https://user-images.githubusercontent.com/19267276/151852351-8528e963-3fba-45ac-ad0e-5f4e70f8c1cd.png)
![image](https://user-images.githubusercontent.com/19267276/151852372-621d33e8-687e-4792-922d-ee7a53c0b5cb.png)

**Comment by DatKyle** [comment]
@tfenster, Thank you.

Do you want to close this issue or leave it open until all the builds are done?

**Comment by tfenster** [comment]
I'll close, but please feel free to add other issues if anything goes wrong. I hope to have a look at #7 on Wednesday
